In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

ModuleNotFoundError: No module named 'pandas'

In [4]:
pip install pandas numpy matplotlib seaborn scikit-learn

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/25/ac/f6ee5250a8881b55bd3aecde9b8cfddea2f2b43e3588bca68a4e9aaf46c8/pandas-2.3.0-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-2.3.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\shamo\anaconda3\lib\site-packages (2.2.2)
Collecting matplotlib
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/a6/da/948a017c3ea13fd4a97afad5fdebe2f5bbc4d28c0654510ce6fd6b06b7bd/matplotlib-3.10.3-cp311-cp311-win_amd64.whl.metadata
  Downloading matplotlib-3.10.3-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting seaborn
  Obtaining dependency information for seaborn from https://files.pythonhosted.org/packages/83/11/00d3c3dfc25ad54e731d91449895a79e4bf2384dc3ac01809010ba88f6d5/seaborn-0.13.2-py3-none-any.whl.metadata
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/f4/5a/ba91b8c57aa37dbd80d5ff958576a9a8c14317b04b671ae7f0d09b00993a/scikit_learn-1.7.0-cp311-cp311-win_amd64.whl.metadata
  Downloading scikit_learn-1.7.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shamo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shamo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shamo\anaconda3\lib\site-packages (from pandas) (2023.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/5e/fe/4029038b4e1c4485cef18e480b0e2cd2d755448bb071eb9977caac80b77b/contourpy-1.3.2-cp311-cp311-win_amd64.whl.metadata
  Downloading contourpy-1.3.2-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: cycler>=0.10 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\shamo\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Collecting scipy>=1.8.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.8.0 from https://files.pythonhosted.org/packages/ab/a7/0ddaf514ce8a8714f6ed243a2b391b41dbb65251affe21ee3077ec45ea9a/scipy-1.15.3-cp311-cp311-win_amd64.whl.metadata
  Downloading scipy-1.15.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB ? eta 0:00:00
Requirement already satisfied: joblib>=1.2.0 in c:\users\shamo\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.1.0 from https://files.pythonhosted.org/packages/32/d5/f9a850d79b0851d1d4ef6456097579a9005b31fea68726a4ae5f2d82ddd9/threadpoolctl-3.6.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\shamo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.0-cp311-cp311-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 14.2 MB/s eta 0:00:01
   --- ------------------------------------ 0.9/11.1 MB 14.1 MB/s eta 0:00:01
   ------ --------------------------------- 1.8/11.1 MB 16.7 MB/s eta 0:00:01
   --------- ------------------------------ 2.6/11.1 MB 16.8 MB/s eta 0:00:01
   ------------ --------------------------- 3.4/11.1 MB 16.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.1 MB 17.6 MB/s eta 0:00:01
   ------------------ --------------------- 5.2/11.1 MB 17.5 MB/s eta 0:00:01
   --------------------- ------------------ 6.1/11.1 MB 17.6 MB/s eta 0:00:01
   ------------------------ --------------- 6.7/11.1 MB 17.0 MB/s eta 0:00:01
   ------------------------- -------------- 7.0/11.1 MB 17.2 MB/s eta 0:00:01
   -------------------------- ------------- 7.4/11.1 MB 15.7 MB/s eta 0:00:01
   --------------------------- ------------ 7.7/11.1 MB 15.0 MB/s eta 0:00:01
   ---------------------------- ----------- 7.8/11.1 MB 13.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.2/11.1 MB 13.5 MB/s eta 0:00:01
   -------------------------------- ------- 9.1/11.1 MB 14.2 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.1 MB 14.2 MB/s eta 0:00:01
   -------------------------------------- - 10.8/11.1 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------  11.1/11.1 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 14.2 MB/s eta 0:00:00
Downloading matplotlib-3.10.3-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.7/8.1 MB 15.3 MB/s eta 0:00:01
   ------- -------------------------------- 1.6/8.1 MB 16.9 MB/s eta 0:00:01
   ------------ --------------------------- 2.6/8.1 MB 18.2 MB/s eta 0:00:01
   --------------- ------------------------ 3.2/8.1 MB 17.1 MB/s eta 0:00:01
   ------------------- -------------------- 3.9/8.1 MB 16.4 MB/s eta 0:00:01
   --------------------- ------------------ 4.3/8.1 MB 16.3 MB/s eta 0:00:01
   ----------------------- ---------------- 4.8/8.1 MB 14.5 MB/s eta 0:00:01
   ------------------------ --------------- 4.9/8.1 MB 13.7 MB/s eta 0:00:01
   ------------------------- -------------- 5.1/8.1 MB 12.5 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 11.4 MB/s eta 0:00:01
   -------------------------- ------------- 5.3/8.1 MB 10.5 MB/s eta 0:00:01
   -------------------------- ------------- 5.4/8.1 MB 9.5 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.1 MB 9.2 MB/s eta 0:00:01
   --------------------------- ------------ 5.6/8.1 MB 8.8 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 8.4 MB/s eta 0:00:01
   ----------------------------- ---------- 5.9/8.1 MB 8.1 MB/s eta 0:00:01
   ------------------------------ --------- 6.1/8.1 MB 7.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.1 MB 7.5 MB/s eta 0:00:01
   -------------------------------- ------- 6.5/8.1 MB 7.4 MB/s eta 0:00:01
   --------------------------------- ------ 6.7/8.1 MB 7.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.0/8.1 MB 7.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 7.2 MB/s eta 0:00:01
   -------------------------------------- - 7.8/8.1 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.1 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 7.1 MB/s eta 0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ---------------------------------------- 294.9/294.9 kB 9.2 MB/s eta 0:00:00
Downloading scikit_learn-1.7.0-cp311-cp311-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.2/10.7 MB 6.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/10.7 MB 7.7 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/10.7 MB 8.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/10.7 MB 9.5 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/10.7 MB 9.5 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/10.7 MB 8.8 MB/s eta 0:00:01
   --------- ------------------------------ 2.6/10.7 MB 8.7 MB/s eta 0:00:01
   ---------- ----------------------------- 2.8/10.7 MB 8.2 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/10.7 MB 8.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.5/10.7 MB 8.0 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/10.7 MB 8.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.2/10.7 MB 8.2 MB/s eta 0:00:01
   ---------------- ----------------------- 4.5/10.7 MB 7.9 MB/s eta 0:00:01
   ------------------ --------------------- 4.8/10.7 MB 7.9 MB/s eta 0:00:01
   ------------------- -------------------- 5.2/10.7 MB 7.9 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/10.7 MB 7.9 MB/s eta 0:00:01
   --------------------- ------------------ 5.8/10.7 MB 7.9 MB/s eta 0:00:01
   ---------------------- ----------------- 6.1/10.7 MB 7.8 MB/s eta 0:00:01
   ----------------------- ---------------- 6.4/10.7 MB 7.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.7/10.7 MB 7.6 MB/s eta 0:00:01
   ------------------------- -------------- 7.0/10.7 MB 7.7 MB/s eta 0:00:01
   --------------------------- ------------ 7.4/10.7 MB 7.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.7/10.7 MB 7.7 MB/s eta 0:00:01
   ----------------------------- ---------- 8.0/10.7 MB 7.6 MB/s eta 0:00:01
   ------------------------------- -------- 8.4/10.7 MB 7.6 MB/s eta 0:00:01
   -------------------------------- ------- 8.6/10.7 MB 7.6 MB/s eta 0:00:01
   --------------------------------- ------ 9.0/10.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------- ----- 9.2/10.7 MB 7.6 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.7 MB 7.5 MB/s eta 0:00:01
   ----------------------------------- ---- 9.6/10.7 MB 7.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.7 MB 7.2 MB/s eta 0:00:01
   ------------------------------------- -- 10.0/10.7 MB 7.2 MB/s eta 0:00:01
   -------------------------------------- - 10.3/10.7 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.7 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  10.7/10.7 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 6.9 MB/s eta 0:00:00
Downloading contourpy-1.3.2-cp311-cp311-win_amd64.whl (222 kB)
   ---------------------------------------- 0.0/222.0 kB ? eta -:--:--
   ---------------------------------------- 222.0/222.0 kB 6.8 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp311-cp311-win_amd64.whl (41.2 MB)
   ---------------------------------------- 0.0/41.2 MB ? eta -:--:--
   ---------------------------------------- 0.4/41.2 MB 12.2 MB/s eta 0:00:04
    --------------------------------------- 0.8/41.2 MB 10.5 MB/s eta 0:00:04
   - -------------------------------------- 1.2/41.2 MB 9.3 MB/s eta 0:00:05
   - -------------------------------------- 1.5/41.2 MB 8.7 MB/s eta 0:00:05
   - -------------------------------------- 2.0/41.2 MB 9.3 MB/s eta 0:00:05
   -- ------------------------------------- 2.5/41.2 MB 9.5 MB/s eta 0:00:05
   -- ------------------------------------- 3.0/41.2 MB 10.2 MB/s eta 0:00:04
   --- ------------------------------------ 3.5/41.2 MB 10.6 MB/s eta 0:00:04
   --- ------------------------------------ 3.9/41.2 MB 10.3 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/41.2 MB 9.5 MB/s eta 0:00:04
   ---- ----------------------------------- 4.5/41.2 MB 9.2 MB/s eta 0:00:05
   ---- ----------------------------------- 4.8/41.2 MB 9.1 MB/s eta 0:00:05
   ---- ----------------------------------- 5.1/41.2 MB 9.1 MB/s eta 0:00:04
   ----- ---------------------------------- 5.5/41.2 MB 8.9 MB/s eta 0:00:04
   ----- ---------------------------------- 5.8/41.2 MB 8.8 MB/s eta 0:00:05
   ----- ---------------------------------- 6.1/41.2 MB 8.9 MB/s eta 0:00:04
   ------ --------------------------------- 6.4/41.2 MB 8.7 MB/s eta 0:00:05
   ------ --------------------------------- 6.7/41.2 MB 8.5 MB/s eta 0:00:05
   ------ --------------------------------- 7.0/41.2 MB 8.6 MB/s eta 0:00:05
   ------- -------------------------------- 7.2/41.2 MB 8.4 MB/s eta 0:00:05
   ------- -------------------------------- 7.4/41.2 MB 8.0 MB/s eta 0:00:05
   ------- -------------------------------- 7.5/41.2 MB 7.8 MB/s eta 0:00:05
   ------- -------------------------------- 7.5/41.2 MB 7.5 MB/s eta 0:00:05
   ------- -------------------------------- 7.6/41.2 MB 7.2 MB/s eta 0:00:05
   ------- -------------------------------- 7.6/41.2 MB 6.9 MB/s eta 0:00:05
   ------- -------------------------------- 7.8/41.2 MB 6.8 MB/s eta 0:00:05
   ------- -------------------------------- 7.9/41.2 MB 6.7 MB/s eta 0:00:05
   ------- -------------------------------- 8.2/41.2 MB 6.6 MB/s eta 0:00:06
   -------- ------------------------------- 8.5/41.2 MB 6.6 MB/s eta 0:00:05
   -------- ------------------------------- 8.8/41.2 MB 6.7 MB/s eta 0:00:05
   -------- ------------------------------- 9.2/41.2 MB 6.8 MB/s eta 0:00:05
   --------- ------------------------------ 9.7/41.2 MB 6.8 MB/s eta 0:00:05
   --------- ------------------------------ 10.2/41.2 MB 6.9 MB/s eta 0:00:05
   ---------- ----------------------------- 10.5/41.2 MB 6.9 MB/s eta 0:00:05
   ---------- ----------------------------- 10.9/41.2 MB 6.9 MB/s eta 0:00:05
   ---------- ----------------------------- 11.1/41.2 MB 6.8 MB/s eta 0:00:05
   ---------- ----------------------------- 11.3/41.2 MB 6.7 MB/s eta 0:00:05
   ----------- ---------------------------- 11.6/41.2 MB 6.7 MB/s eta 0:00:05
   ----------- ---------------------------- 12.0/41.2 MB 6.6 MB/s eta 0:00:05
   ----------- ---------------------------- 12.2/41.2 MB 6.5 MB/s eta 0:00:05
   ----------- ---------------------------- 12.3/41.2 MB 6.4 MB/s eta 0:00:05
   ------------ --------------------------- 12.5/41.2 MB 6.3 MB/s eta 0:00:05
   ------------ --------------------------- 12.6/41.2 MB 6.2 MB/s eta 0:00:05
   ------------ --------------------------- 12.7/41.2 MB 6.1 MB/s eta 0:00:05
   ------------ --------------------------- 12.9/41.2 MB 5.9 MB/s eta 0:00:05
   ------------ --------------------------- 13.1/41.2 MB 5.8 MB/s eta 0:00:05
   ------------ --------------------------- 13.3/41.2 MB 5.7 MB/s eta 0:00:05
   ------------- -------------------------- 13.5/41.2 MB 5.6 MB/s eta 0:00:05
   ------------- -------------------------- 13.5/41.2 MB 5.5 MB/s eta 0:00:06
   ------------- -------------------------- 13.7/41.2 MB 5.4 MB/s eta 0:00:06
   ------------- -------------------------- 13.7/41.2 MB 5.3 MB/s eta 0:00:06
   ------------- -------------------------- 13.8/41.2 MB 5.2 MB/s eta 0:00:06
   ------------- -------------------------- 14.0/41.2 MB 5.2 MB/s eta 0:00:06
   ------------- -------------------------- 14.2/41.2 MB 5.2 MB/s eta 0:00:06
   ------------- -------------------------- 14.4/41.2 MB 5.1 MB/s eta 0:00:06
   -------------- ------------------------- 14.8/41.2 MB 5.2 MB/s eta 0:00:06
   -------------- ------------------------- 15.1/41.2 MB 5.1 MB/s eta 0:00:06
   --------------- ------------------------ 15.5/41.2 MB 5.2 MB/s eta 0:00:05
   --------------- ------------------------ 15.9/41.2 MB 5.2 MB/s eta 0:00:05
   --------------- ------------------------ 16.3/41.2 MB 5.2 MB/s eta 0:00:05
   ---------------- ----------------------- 16.8/41.2 MB 5.2 MB/s eta 0:00:05
   ---------------- ----------------------- 17.2/41.2 MB 5.3 MB/s eta 0:00:05
   ----------------- ---------------------- 17.7/41.2 MB 5.6 MB/s eta 0:00:05
   ----------------- ---------------------- 18.0/41.2 MB 6.0 MB/s eta 0:00:04
   ----------------- ---------------------- 18.3/41.2 MB 6.1 MB/s eta 0:00:04
   ------------------ --------------------- 18.6/41.2 MB 6.1 MB/s eta 0:00:04
   ------------------ --------------------- 18.9/41.2 MB 6.1 MB/s eta 0:00:04
   ------------------ --------------------- 19.2/41.2 MB 6.1 MB/s eta 0:00:04
   ------------------ --------------------- 19.4/41.2 MB 6.0 MB/s eta 0:00:04
   ------------------- -------------------- 19.8/41.2 MB 6.0 MB/s eta 0:00:04
   ------------------- -------------------- 20.1/41.2 MB 5.9 MB/s eta 0:00:04
   ------------------- -------------------- 20.5/41.2 MB 6.0 MB/s eta 0:00:04
   -------------------- ------------------- 20.8/41.2 MB 5.9 MB/s eta 0:00:04
   -------------------- ------------------- 21.1/41.2 MB 5.8 MB/s eta 0:00:04
   -------------------- ------------------- 21.4/41.2 MB 5.9 MB/s eta 0:00:04
   --------------------- ------------------ 21.7/41.2 MB 5.9 MB/s eta 0:00:04
   --------------------- ------------------ 22.1/41.2 MB 6.0 MB/s eta 0:00:04
   --------------------- ------------------ 22.5/41.2 MB 6.1 MB/s eta 0:00:04
   ---------------------- ----------------- 22.7/41.2 MB 6.2 MB/s eta 0:00:03
   ---------------------- ----------------- 23.1/41.2 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 23.4/41.2 MB 6.5 MB/s eta 0:00:03
   ---------------------- ----------------- 23.6/41.2 MB 6.6 MB/s eta 0:00:03
   ----------------------- ---------------- 24.0/41.2 MB 7.3 MB/s eta 0:00:03
   ----------------------- ---------------- 24.4/41.2 MB 7.5 MB/s eta 0:00:03
   ----------------------- ---------------- 24.7/41.2 MB 7.6 MB/s eta 0:00:03
   ------------------------ --------------- 24.9/41.2 MB 7.6 MB/s eta 0:00:03
   ------------------------ --------------- 25.1/41.2 MB 7.4 MB/s eta 0:00:03
   ------------------------ --------------- 25.3/41.2 MB 7.4 MB/s eta 0:00:03
   ------------------------ --------------- 25.5/41.2 MB 7.4 MB/s eta 0:00:03
   ------------------------- -------------- 25.9/41.2 MB 7.3 MB/s eta 0:00:03
   ------------------------- -------------- 26.1/41.2 MB 7.3 MB/s eta 0:00:03
   ------------------------- -------------- 26.5/41.2 MB 7.1 MB/s eta 0:00:03
   -------------------------- ------------- 26.8/41.2 MB 7.2 MB/s eta 0:00:03
   -------------------------- ------------- 27.3/41.2 MB 7.1 MB/s eta 0:00:02
   -------------------------- ------------- 27.7/41.2 MB 7.1 MB/s eta 0:00:02
   --------------------------- ------------ 28.2/41.2 MB 7.2 MB/s eta 0:00:02
   --------------------------- ------------ 28.5/41.2 MB 7.2 MB/s eta 0:00:02
   --------------------------- ------------ 28.7/41.2 MB 7.1 MB/s eta 0:00:02
   ---------------------------- ----------- 28.9/41.2 MB 7.2 MB/s eta 0:00:02
   ---------------------------- ----------- 29.2/41.2 MB 7.1 MB/s eta 0:00:02
   ---------------------------- ----------- 29.6/41.2 MB 7.2 MB/s eta 0:00:02
   ----------------------------- ---------- 30.0/41.2 MB 7.2 MB/s eta 0:00:02
   ----------------------------- ---------- 30.3/41.2 MB 7.1 MB/s eta 0:00:02
   ----------------------------- ---------- 30.8/41.2 MB 7.3 MB/s eta 0:00:02
   ------------------------------ --------- 31.2/41.2 MB 7.2 MB/s eta 0:00:02
   ------------------------------ --------- 31.5/41.2 MB 7.3 MB/s eta 0:00:02
   ------------------------------ --------- 31.8/41.2 MB 7.3 MB/s eta 0:00:02
   ------------------------------- -------- 32.1/41.2 MB 7.2 MB/s eta 0:00:02
   ------------------------------- -------- 32.4/41.2 MB 7.2 MB/s eta 0:00:02
   ------------------------------- -------- 32.6/41.2 MB 7.2 MB/s eta 0:00:02
   ------------------------------- -------- 32.8/41.2 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 33.1/41.2 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 33.4/41.2 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 33.6/41.2 MB 7.0 MB/s eta 0:00:02
   -------------------------------- ------- 33.8/41.2 MB 6.9 MB/s eta 0:00:02
   -------------------------------- ------- 33.8/41.2 MB 6.9 MB/s eta 0:00:02
   -------------------------------- ------- 33.9/41.2 MB 6.5 MB/s eta 0:00:02

In [6]:
import pandas as pd # data manipulation
import numpy as np # numerical python - linear algebra

from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [8]:
df = pd.read_csv('PB_All_2000_2021.csv', sep=';')
df

,id,date,NH4,BSK5,Suspended,O2,NO3,NO2,SO4,PO4,CL
0,1,17.02.2000,0.330,2.77,12.0,12.30,9.50,0.057,154.00,0.454,289.50
1,1,11.05.2000,0.044,3.00,51.6,14.61,17.75,0.034,352.00,0.090,1792.00
2,1,11.09.2000,0.032,2.10,24.5,9.87,13.80,0.173,416.00,0.200,2509.00
3,1,13.12.2000,0.170,2.23,35.6,12.40,17.13,0.099,275.20,0.377,1264.00
4,1,02.03.2001,0.000,3.03,48.8,14.69,10.00,0.065,281.60,0.134,1462.00
...,...,...,...,...,...,...,...,...,...,...,...
2856,22,06.10.2020,0.046,2.69,3.6,8.28,3.80,0.038,160.00,0.726,77.85
2857,22,27.10.2020,0.000,1.52,0.5,11.26,0.56,0.031,147.20,0.634,71.95
2858,22,03.12.2020,0.034,0.29,0.8,11.09,2.58,0.042,209.92,0.484,61.17
2859,22,12.01.2021,0.000,2.10,0.0,14.31,3.94,0.034,121.60,0.424,63.49
2860,22,10.02.2021,0.000,1.78,0.0,14.30,6.30,0.033,134.40,0.582,66.31

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2861 entries, 0 to 2860
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         2861 non-null   int64
 1   date       2861 non-null   object
 2   NH4        2858 non-null   float64
 3   BSK5       2860 non-null   float64
 4   Suspended  2845 non-null   float64
 5   O2         2858 non-null   float64
 6   NO3        2860 non-null   float64
 7   NO2        2858 non-null   float64
 8   SO4        2812 non-null   float64
 9   PO4        2833 non-null   float64
 10  CL         2812 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 246.0+ KB

In [12]:
df.shape

(2861, 11)

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,2861.0,12.397064,6.084226,1.00,8.0000,14.000,16.00000,22.000
NH4,2858.0,0.758734,2.486247,0.00,0.0800,0.220,0.50000,39.427
BSK5,2860.0,4.316182,2.973997,0.00,2.1600,3.800,5.80000,50.900
Suspended,2845.0,12.931905,16.543097,0.00,6.0000,10.000,15.00000,595.000
O2,2858.0,9.508902,4.428260,0.00,7.0925,8.995,11.52000,90.000
NO3,2860.0,4.316846,6.881188,0.00,1.3900,2.800,5.58250,133.400
NO2,2858.0,0.246128,2.182777,0.00,0.0300,0.059,0.12575,109.000
SO4,2812.0,59.362313,96.582641,0.00,27.0525,37.800,64.64000,3573.400
PO4,2833.0,0.418626,0.771326,0.00,0.1300,0.270,0.47000,13.879
CL,2812.0,93.731991,394.512184,0.02,26.8000,33.900,45.60750,5615.280

In [16]:
df.isnull().sum()

id            0
date          0
NH4           3
BSK5          1
Suspended    16
O2            3
NO3           1
NO2           3
SO4          49
PO4          28
CL           49
dtype: int64

In [18]:
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')
df

,id,date,NH4,BSK5,Suspended,O2,NO3,NO2,SO4,PO4,CL
0,1,2000-02-17,0.330,2.77,12.0,12.30,9.50,0.057,154.00,0.454,289.50
1,1,2000-05-11,0.044,3.00,51.6,14.61,17.75,0.034,352.00,0.090,1792.00
2,1,2000-09-11,0.032,2.10,24.5,9.87,13.80,0.173,416.00,0.200,2509.00
3,1,2000-12-13,0.170,2.23,35.6,12.40,17.13,0.099,275.20,0.377,1264.00
4,1,2001-03-02,0.000,3.03,48.8,14.69,10.00,0.065,281.60,0.134,1462.00
...,...,...,...,...,...,...,...,...,...,...,...
2856,22,2020-10-06,0.046,2.69,3.6,8.28,3.80,0.038,160.00,0.726,77.85
2857,22,2020-10-27,0.000,1.52,0.5,11.26,0.56,0.031,147.20,0.634,71.95
2858,22,2020-12-03,0.034,0.29,0.8,11.09,2.58,0.042,209.92,0.484,61.17
2859,22,2021-01-12,0.000,2.10,0.0,14.31,3.94,0.034,121.60,0.424,63.49
2860,22,2021-02-10,0.000,1.78,0.0,14.30,6.30,0.033,134.40,0.582,66.31

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2861 entries, 0 to 2860
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         2861 non-null   int64
 1   date       2861 non-null   datetime64[ns]
 2   NH4        2858 non-null   float64
 3   BSK5       2860 non-null   float64
 4   Suspended  2845 non-null   float64
 5   O2         2858 non-null   float64
 6   NO3        2860 non-null   float64
 7   NO2        2858 non-null   float64
 8   SO4        2812 non-null   float64
 9   PO4        2833 non-null   float64
 10  CL         2812 non-null   float64
dtypes: datetime64[ns](1), float64(9), int64(1)
memory usage: 246.0 KB

In [22]:
df = df.sort_values(by=['id', 'date'])
df.head()

,id,date,NH4,BSK5,Suspended,O2,NO3,NO2,SO4,PO4,CL
0,1,2000-02-17,0.330,2.77,12.0,12.30,9.50,0.057,154.0,0.454,289.5
1,1,2000-05-11,0.044,3.00,51.6,14.61,17.75,0.034,352.0,0.090,1792.0
2,1,2000-09-11,0.032,2.10,24.5,9.87,13.80,0.173,416.0,0.200,2509.0
3,1,2000-12-13,0.170,2.23,35.6,12.40,17.13,0.099,275.2,0.377,1264.0
4,1,2001-03-02,0.000,3.03,48.8,14.69,10.00,0.065,281.6,0.134,1462.0

In [24]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df.head()

,id,date,NH4,BSK5,Suspended,O2,NO3,NO2,SO4,PO4,CL,year,month
0,1,2000-02-17,0.330,2.77,12.0,12.30,9.50,0.057,154.0,0.454,289.5,2000,2
1,1,2000-05-11,0.044,3.00,51.6,14.61,17.75,0.034,352.0,0.090,1792.0,2000,5
2,1,2000-09-11,0.032,2.10,24.5,9.87,13.80,0.173,416.0,0.200,2509.0,2000,9
3,1,2000-12-13,0.170,2.23,35.6,12.40,17.13,0.099,275.2,0.377,1264.0,2000,12
4,1,2001-03-02,0.000,3.03,48.8,14.69,10.00,0.065,281.6,0.134,1462.0,2001,3

In [26]:
df.columns

Index(['id', 'date', 'NH4', 'BSK5', 'Suspended', 'O2', 'NO3', 'NO2', 'SO4',
       'PO4', 'CL', 'year', 'month'],
      dtype='object')

In [28]:
pollutants = ['O2', 'NO3', 'NO2', 'SO4',
       'PO4', 'CL']